"""Robustness of H1 and H3 to the BERTopic outlier reassignment.

Re-estimates the primary H1 and H3 specifications with (a) all reassigned
outliers excluded and (b) only low-confidence reassignments excluded (see
topic_layer/assignment_confidence.py), alongside the full sample. H2's
primary model does not use topic labels, so it is unaffected.

Usage:
    python -m validation.outlier_robustness
"""

import argparse
from pathlib import Path

import pandas as pd

from linking_layer.h1_reanalysis import build_utterance_frame, fit_logit, party_summary
from outcome_layer.h3_reanalysis import build_panel, effect_row, fit_ols

H1_FORMULA = "y ~ opp + C(topic) + C(chair) + log_words"
H3_FORMULA = "attention_next ~ attention + present + conflict_any_z + C(topic) + C(debate_id)"


def run(processed_dir: Path) -> None:
    confidence = pd.read_parquet(processed_dir / "topic_assignment_confidence.parquet")
    exclusions = {
        "Full sample": None,
        "Reassigned outliers excluded": confidence.loc[confidence["was_outlier"], ["debate_id", "seq_index"]],
        "Low-confidence reassignments excluded": confidence.loc[confidence["low_confidence"], ["debate_id", "seq_index"]],
    }

    print("H1...")
    utts = build_utterance_frame(processed_dir).rename(columns={"sitting": "debate_id"})
    h1_rows = []
    for label, keys in exclusions.items():
        data = utts
        if keys is not None:
            drop = data.set_index(["debate_id", "seq_index"]).index.isin(keys.set_index(["debate_id", "seq_index"]).index)
            data = data[~drop]
        data = data.rename(columns={"debate_id": "sitting"}).assign(y=lambda d: d["y_any_w3"].astype(int))
        result, data = fit_logit(data, H1_FORMULA)
        h1_rows.append(party_summary(label, result, data))
    h1 = pd.DataFrame(h1_rows)

    print("H3...")
    h3_rows = []
    for label, keys in exclusions.items():
        panel = build_panel(processed_dir, exclude=keys)
        base = panel.dropna(subset=["attention_next"])
        result, data = fit_ols(base, H3_FORMULA)
        h3_rows.append(effect_row(label, result, data, "conflict_any_z", base["attention"].mean()))
    h3 = pd.DataFrame(h3_rows)

    lines = [
        "# Outlier-Reassignment Robustness",
        "",
        "Generated by `src/validation/outlier_robustness.py`. Primary H1 and H3 specifications re-estimated "
        "without topic assignments that came from BERTopic's forced outlier reassignment. H2's primary model "
        "does not use topic labels.",
        "",
        "## H1: Opposition vs Government intervention (logit, two-way clustered by sitting and speaker)",
        "",
        "| Sample | N | N Opp | OR [95% CI] | p | AME pp [95% CI] | TOST p (+/-5pp) | TOST p (+/-2pp) |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for _, r in h1.iterrows():
        lines.append(
            f"| {r.specification} | {r.n_utterances:,} | {r.n_opposition:,} | {r.OR:.3f} [{r.OR_lo95:.3f}, {r.OR_hi95:.3f}] | "
            f"{r.p:.3f} | {r.AME_pp:+.2f} [{r.AME_lo95_pp:+.2f}, {r.AME_hi95_pp:+.2f}] | {r.tost_p_pp5:.4f} | {r.tost_p_pp2:.4f} |"
        )
    lines += [
        "",
        "## H3: conflict effect on next-sitting attention (topic + sitting FE, two-way clustered)",
        "",
        "| Sample | Cells | Present | Effect per SD [95% CI] | % of mean attention [95% CI] | p | TOST p (+/-10%) |",
        "|---|---|---|---|---|---|---|",
    ]
    for _, r in h3.iterrows():
        lines.append(
            f"| {r.specification} | {r.n_cells:,} | {r.n_present:,} | {r.beta_per_sd:+.6f} [{r.lo95:+.6f}, {r.hi95:+.6f}] | "
            f"{r.pct_of_mean:+.1f}% [{r.pct_lo95:+.1f}%, {r.pct_hi95:+.1f}%] | {r.p_two_sided:.3f} | {r.tost_p:.4f} |"
        )
    lines.append("")
    (processed_dir / "outlier_robustness_report.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {processed_dir / 'outlier_robustness_report.md'}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--processed-dir", default="data/processed")
    args = parser.parse_args()
    run(Path(args.processed_dir))
