"""Assignment confidence for the BERTopic outlier reassignment.

train_bertopic.py reassigns every HDBSCAN outlier to its nearest topic by
embedding similarity and then calls update_topics, so the saved topic_id no
longer records which utterances were outliers. The fitted HDBSCAN model kept
in the saved BERTopic object still holds the original cluster labels
(-1 = outlier); this module recovers them and scores each assignment:

  - was_outlier: the utterance was reassigned rather than clustered.
  - centroid_similarity: cosine similarity of the utterance embedding to the
    centroid of its assigned topic's core (non-outlier) members.
  - margin: centroid_similarity minus the similarity to the nearest other
    topic centroid.
  - low_confidence: a reassigned utterance less similar to its topic centroid
    than the 10th percentile of that topic's core members.

It also reports how often the downstream two-stage classifier agrees with the
cluster-derived training label, separately for core and reassigned utterances.

Usage:
    python -m topic_layer.assignment_confidence
"""

import argparse
from pathlib import Path

import joblib
import numpy as np
import pandas as pd

from topic_layer.train_classifier import NON_POLICY_LABEL

LOW_CONFIDENCE_PERCENTILE = 10


def recover_outlier_flags(models_dir: Path) -> np.ndarray:
    model = joblib.load(models_dir / "bertopic")
    return np.asarray(model.hdbscan_model.labels_) == -1


def score_assignments(embeddings: np.ndarray, topic_ids: np.ndarray, was_outlier: np.ndarray) -> pd.DataFrame:
    norm = embeddings / np.linalg.norm(embeddings, axis=1, keepdims=True)
    topics = np.unique(topic_ids)
    centroids = np.vstack([norm[(topic_ids == t) & ~was_outlier].mean(axis=0) for t in topics])
    centroids /= np.linalg.norm(centroids, axis=1, keepdims=True)
    index = {t: i for i, t in enumerate(topics)}

    sims = norm @ centroids.T
    own = np.array([index[t] for t in topic_ids])
    assigned = sims[np.arange(len(sims)), own]
    sims[np.arange(len(sims)), own] = -np.inf
    margin = assigned - sims.max(axis=1)

    scores = pd.DataFrame({"topic_id": topic_ids, "was_outlier": was_outlier,
                           "centroid_similarity": assigned, "margin": margin})
    core = scores[~scores["was_outlier"]]
    floor = core.groupby("topic_id")["centroid_similarity"].quantile(LOW_CONFIDENCE_PERCENTILE / 100)
    scores["low_confidence"] = scores["was_outlier"] & (scores["centroid_similarity"] < scores["topic_id"].map(floor))
    return scores


def write_report(path: Path, scores: pd.DataFrame) -> None:
    policy = scores[scores["predicted_label"] != NON_POLICY_LABEL]
    lines = [
        "# Topic Assignment Confidence Report",
        "",
        "Generated by `src/topic_layer/assignment_confidence.py`.",
        "",
        "## Outlier reassignment",
        "",
        f"- Utterances clustered by BERTopic: {len(scores):,}.",
        f"- HDBSCAN outliers reassigned to the nearest topic: {int(scores.was_outlier.sum()):,} "
        f"({scores.was_outlier.mean():.1%}).",
        f"- Among utterances the two-stage classifier labels as Policy ({len(policy):,}): "
        f"{policy.was_outlier.mean():.1%} were reassigned outliers; {policy.low_confidence.mean():.1%} are "
        f"low-confidence reassignments (below the {LOW_CONFIDENCE_PERCENTILE}th percentile of their topic's "
        "core-member similarity).",
        "",
        "## Similarity to assigned topic centroid",
        "",
        "| Group | N | Median similarity | 10th pct | Median margin over next topic | Share with margin < 0.02 |",
        "|---|---|---|---|---|---|",
    ]
    for label, g in [("Core members", scores[~scores.was_outlier]), ("Reassigned outliers", scores[scores.was_outlier])]:
        lines.append(
            f"| {label} | {len(g):,} | {g.centroid_similarity.median():.3f} | {g.centroid_similarity.quantile(0.1):.3f} | "
            f"{g.margin.median():.3f} | {(g.margin < 0.02).mean():.1%} |"
        )
    lines += [
        "",
        "## Classifier agreement with cluster-derived labels",
        "",
        "The classifier was trained on labels derived from cluster membership (including reassigned outliers). "
        "Agreement between its prediction and the cluster-derived label is reported here as a consistency "
        "check, not as accuracy against independent annotation.",
        "",
        "| Group | Agreement (all) | Agreement (cluster label is Policy) |",
        "|---|---|---|",
    ]
    for label, g in [("Core members", scores[~scores.was_outlier]),
                     ("Reassigned outliers", scores[scores.was_outlier]),
                     ("Low-confidence reassigned", scores[scores.low_confidence])]:
        agree = (g["predicted_label"] == g["cluster_target"]).mean()
        pol = g[g["cluster_target"] != NON_POLICY_LABEL]
        agree_pol = (pol["predicted_label"] == pol["cluster_target"]).mean() if len(pol) else float("nan")
        lines.append(f"| {label} | {agree:.1%} | {agree_pol:.1%} |")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def run(processed_dir: Path, models_dir: Path) -> None:
    topics = pd.read_parquet(processed_dir / "topics.parquet")
    embeddings = np.load(models_dir / "embeddings.npy")
    print("Recovering HDBSCAN outlier labels from the saved BERTopic model...")
    was_outlier = recover_outlier_flags(models_dir)
    if not (len(topics) == len(embeddings) == len(was_outlier)):
        raise ValueError("topics.parquet, embeddings.npy and the HDBSCAN labels are not aligned")

    print("Scoring assignments...")
    scores = score_assignments(embeddings, topics["topic_id"].to_numpy(), was_outlier)
    scores.insert(0, "seq_index", topics["seq_index"].to_numpy())
    scores.insert(0, "debate_id", topics["debate_id"].to_numpy())

    labeled = pd.read_excel(processed_dir / "topic_taxonomy_labeled.xlsx", sheet_name="Human-Labelled Taxonomy")
    cluster_target = labeled.set_index("topic_id").apply(
        lambda r: r["label"] if r["label_type"] == "Policy" else NON_POLICY_LABEL, axis=1
    )
    scores["cluster_target"] = scores["topic_id"].map(cluster_target).fillna(NON_POLICY_LABEL)
    predictions = pd.read_parquet(processed_dir / "utterance_policy_labels_two_stage.parquet")
    scores = scores.merge(predictions[["debate_id", "seq_index", "predicted_label"]], on=["debate_id", "seq_index"], how="left")

    scores.to_parquet(processed_dir / "topic_assignment_confidence.parquet", index=False)
    write_report(processed_dir / "topic_assignment_confidence_report.md", scores)
    print(f"Wrote {processed_dir / 'topic_assignment_confidence_report.md'}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--processed-dir", default="data/processed")
    parser.add_argument("--models-dir", default="models")
    args = parser.parse_args()
    run(Path(args.processed_dir), Path(args.models_dir))
